### ISSUE TITLE
cancel_order() always returns success

### ISSUE THREAD

**Issue by Fables1013** [Dimfred/imxpy#1]
From what I can tell the Client.cancel_order() function is returning a success regardless of the order_id that's passed in and it doesn't seem to actually be cancelling the order when passed a real order_id on the main net

**Comment by Dimfred** [comment]
Found the error, so it was partially on my side it should be hopefully fixed with: https://github.com/Dimfred/imxpy/commit/0ef37644b99099ccfc4ef098ac2758d711c90da7

On one side, I didn't look at the params probably, on the other side there is an issue with the function in the `imx-sdk`, seems it has to be called one to return a function which has to be called again? Looks wrong to me whatever it seems to work for me now.

**Comment by Dimfred** [comment]
Closing since this is fixed.
